"""Independent R-reference and probabilistic checks for the HMM solver."""

import itertools
import json
import math
import warnings
from pathlib import Path

import pytest
import torch

from cebmf_torch import cEBMF
from cebmf_torch.cebmf.cebmf import normal_means_loglik
from cebmf_torch.cebnm.hmm import (
    _component_log_emission,
    _log_smoother,
    _posterior_moments,
    _smooth,
    fit_ash_hmm,
    hmm_neg_posterior_means,
    hmm_pos_posterior_means,
    hmm_posterior_means,
)
from cebmf_torch.priors import PRIOR_REGISTRY

REFERENCE = json.loads((Path(__file__).parent / "fixtures" / "hmm_reference.json").read_text())


@pytest.fixture(scope="module", autouse=True)
def single_thread_for_small_tests():
    previous = torch.get_num_threads()
    torch.set_num_threads(1)
    yield
    torch.set_num_threads(previous)


def tensor(x):
    return torch.as_tensor(x, dtype=torch.float64)


@pytest.mark.parametrize("case", REFERENCE)
def test_matches_fsusie_reference(case):
    """Saved outputs generated by base R, with no Python solver involved."""
    ref = REFERENCE[case]
    inputs = {k: (v[0] if isinstance(v, list) and len(v) == 1 else v) for k, v in ref["input"].items()}
    inputs["y"], inputs["se"] = tensor(inputs["y"]), tensor(inputs["se"])
    result = fit_ash_hmm(**inputs)
    # The bounded scalar optimizer differs from R's Brent optimizer; allow
    # its numerical tolerance to propagate through one-sided mean updates.
    tolerance = 2e-6 if inputs.get("nonnegative_state_means") and inputs.get("learn_state_means", True) else 2e-9
    for field in ("post_mean", "post_mean2", "pi0_null", "lfsr", "state_probability", "history", "objective_history"):
        torch.testing.assert_close(getattr(result, field), tensor(ref[field]), atol=tolerance, rtol=tolerance)
    torch.testing.assert_close(result.log_likelihood, tensor(ref["log_likelihood"][0]), atol=tolerance, rtol=tolerance)
    for field in ("mu", "prior_sd", "transition", "init_prob", "mixture_weight"):
        torch.testing.assert_close(result.model_param[field], tensor(ref[field]), atol=tolerance, rtol=tolerance)
    assert result.state_counts == ref["state_counts"]


def test_smoother_matches_exhaustive_path_enumeration():
    """Enumerating every path independently checks orientation and endpoints."""
    emission = tensor([[0.8, 0.1], [0.2, 0.6], [0.4, 0.3], [0.1, 0.9]])
    transition = tensor([[0.85, 0.15], [0.4, 0.6]])
    init = tensor([0.2, 0.8])
    probability = torch.zeros_like(emission)
    counts = torch.zeros_like(transition)
    evidence = 0.0
    for path in itertools.product(range(2), repeat=4):
        weight = init[path[0]] * emission[0, path[0]]
        for t in range(1, 4):
            weight = weight * transition[path[t - 1], path[t]] * emission[t, path[t]]
        evidence += float(weight)
        for t, state in enumerate(path):
            probability[t, state] += weight
        for t in range(1, 4):
            counts[path[t - 1], path[t]] += weight
    for smoother in (_smooth, _log_smoother):
        ll, gamma, xi = smoother(emission.log(), transition, init)
        torch.testing.assert_close(ll, tensor(math.log(evidence)))
        torch.testing.assert_close(gamma, probability / evidence)
        torch.testing.assert_close(xi, counts / evidence)
        torch.testing.assert_close(gamma.sum(1), torch.ones(4, dtype=torch.float64))
        torch.testing.assert_close(xi.sum(), tensor(3.0))


def test_log_fallback_for_unreachable_largest_emission():
    emission = tensor([[-1000.0, 0.0], [-1001.0, 0.0]])
    ll, gamma, counts = _smooth(emission, torch.eye(2, dtype=torch.float64), tensor([1.0, 0.0]))
    torch.testing.assert_close(ll, tensor(-2001.0))
    torch.testing.assert_close(gamma, tensor([[1.0, 0.0], [1.0, 0.0]]))
    torch.testing.assert_close(counts, tensor([[1.0, 0.0], [0.0, 0.0]]))


def test_one_sided_emission_and_moments_against_numerical_integration():
    """Integrate the actual prior times likelihood, independently of formulas."""
    y, se, mu, sd = tensor([-2.0, 0.8]), tensor([0.5, 0.7]), tensor([0.4]), tensor([0.9])
    grid = torch.linspace(0, 10, 100001, dtype=torch.float64)
    normal = torch.distributions.Normal
    prior = normal(mu[0], sd[0]).log_prob(grid).exp() / normal(0, 1).cdf(mu[0] / sd[0])
    density = normal(grid, se[:, None]).log_prob(y[:, None]).exp() * prior
    marginal = torch.trapezoid(density, grid, dim=1)
    expected_mean = torch.trapezoid(density * grid, grid, dim=1) / marginal
    expected_second = torch.trapezoid(density * grid.square(), grid, dim=1) / marginal
    emission = _component_log_emission(y, se, mu, sd, True).flatten().exp()
    mean, second, _, _ = _posterior_moments(y, se, mu, sd, torch.ones(2, 1, 1, dtype=torch.float64), True)
    torch.testing.assert_close(emission, marginal, rtol=1e-6, atol=1e-10)
    torch.testing.assert_close(mean, expected_mean, rtol=1e-6, atol=1e-8)
    torch.testing.assert_close(second, expected_second, rtol=1e-6, atol=1e-8)


def test_negative_is_reflection_and_has_nonpositive_support():
    y, se = tensor([-20, -1, 0.1, 2.0, 3.0]), tensor([0.1, 0.5, 0.6, 0.4, 0.3])
    settings = {"mu": [0, 1.2, 3.4], "prior_sd": [0, 0.4, 1], "maxiter": 8, "prune_states": False}
    positive = hmm_pos_posterior_means(None, y, se, **settings)
    negative = hmm_neg_posterior_means(None, -y, se, **{**settings, "mu": [0, -1.2, -3.4]})
    assert (positive.post_mean >= 0).all() and (negative.post_mean <= 0).all()
    for field in ("post_mean2", "pi0_null", "lfsr", "loss", "state_probability"):
        torch.testing.assert_close(getattr(positive, field), getattr(negative, field))
    torch.testing.assert_close(positive.post_mean, -negative.post_mean)
    torch.testing.assert_close(positive.model_param["mu"], -negative.model_param["mu"])
    torch.testing.assert_close(positive.lfsr, positive.pi0_null)
    assert torch.isfinite(positive.post_mean2).all()
    assert (positive.post_mean2 >= positive.post_mean.square()).all()
    with pytest.raises(ValueError, match="strictly positive"):
        hmm_neg_posterior_means(None, y, se, **settings)
    with pytest.raises(ValueError, match="requires"):
        hmm_pos_posterior_means(None, y, se, nonnegative_state_means=False)


@pytest.mark.parametrize("dtype", [torch.float32, torch.float64])
def test_null_singleton_and_scalar_se(dtype):
    result = fit_ash_hmm(torch.zeros(1, dtype=dtype), tensor(0.5), mu=[0], prior_sd=[0], maxiter=2)
    assert result.post_mean.dtype == result.post_mean2.dtype == result.loss.dtype == dtype
    torch.testing.assert_close(result.post_mean, torch.zeros(1, dtype=dtype))
    torch.testing.assert_close(result.pi0_null, torch.ones(1, dtype=dtype))
    torch.testing.assert_close(result.lfsr, torch.ones(1, dtype=dtype))
    torch.testing.assert_close(result.loss, torch.tensor(math.log(0.5) + 0.5 * math.log(2 * math.pi), dtype=dtype))


def test_full_marginal_likelihood_gives_valid_kl():
    y, se = tensor([0.1, -0.1, 2.1, 1.9, 0.0]), tensor([0.3, 0.4, 0.5, 0.4, 0.3])
    result = fit_ash_hmm(y, se, maxiter=6)
    kl = normal_means_loglik(y, se, result.post_mean, result.post_mean2) + result.loss
    assert kl >= -1e-10
    torch.testing.assert_close(result.loss, -result.history[-1])


def test_lfsr_counts_zero_atom_in_both_sign_tails():
    mu, initial = tensor([0, 1, -1]), tensor([0.6, 0.1, 0.3])
    result = fit_ash_hmm(tensor([0]), tensor(1), mu=mu, prior_sd=[0], init_prob=initial, maxiter=0)
    # A single observation with three atoms: Bayes' rule gives exact weights.
    weights = initial * (-0.5 * mu.square()).exp()
    weights /= weights.sum()
    expected = weights[0] + torch.minimum(weights[1], weights[2])
    torch.testing.assert_close(result.lfsr, expected.reshape(1))
    assert result.lfsr[0] > 0.5
    assert result.lfsr[0] > result.pi0_null[0]


def test_gaussian_lfsr_retains_small_tail_probabilities():
    y = tensor([0, 10 * math.sqrt(2), -10 * math.sqrt(2)])
    result = fit_ash_hmm(
        y, tensor(1), mu=[0], prior_sd=[0, 1], init_rho=[[0, 1]], null_state="adaptive", maxiter=0
    )
    # The posterior is N(y/2, 1/2); use erfc as an independent normal-tail oracle.
    tail = 0.5 * math.erfc(10 / math.sqrt(2))
    torch.testing.assert_close(result.lfsr, tensor([0.5, tail, tail]), atol=0, rtol=1e-12)


@pytest.mark.parametrize(
    "y,se",
    [
        ([], []),
        ([0, math.nan], [1, 1]),
        ([0], [0]),
        ([0], [math.inf]),
        ([0, 1], [1, -1]),
        ([[0, 1]], [1, 1]),
        ([0, 1], [1, 1, 1]),
    ],
)
def test_invalid_observations_are_rejected(y, se):
    with pytest.raises(ValueError):
        fit_ash_hmm(tensor(y), tensor(se))


@pytest.mark.parametrize("side", ["L", "F"])
@pytest.mark.parametrize("prior", ["hmm", "hmm_pos", "hmm_neg"])
def test_registry_cebmf_ignores_covariates_once(side, prior):
    y = torch.arange(1, 97, dtype=torch.float64).reshape(8, 12) / 96
    settings = {
        "mu": [0, -1] if prior == "hmm_neg" else [0, 1],
        "prior_sd": [0, 0.4],
        "maxiter": 3,
        "penalty": 1.5,
    }
    kwargs = {f"prior_{side}": prior, f"prior_{side}_kwargs": settings}
    # Even malformed side information is ignored before device/shape handling.
    external = {f"X_{side.lower()}": tensor([math.nan]), "self_row_cov" if side == "L" else "self_col_cov": True}
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        model = cEBMF(y, K=1, S=1, device=torch.device("cpu"), allow_backfitting=False, **kwargs, **external)
        model.initialise_factors()
        model.fit(2)
    messages = [str(w.message) for w in caught if "HMM specified" in str(w.message)]
    assert len(messages) == 1 and f"for {side}" in messages[0]
    assert "'emdn' or 'spiked_emdn'" in messages[0]
    assert getattr(model.covariate, f"X_{side.lower()}") is None
    plain = cEBMF(y, K=1, S=1, device=torch.device("cpu"), allow_backfitting=False, **kwargs)
    plain.initialise_factors()
    plain.fit(2)
    torch.testing.assert_close(model.F, plain.F)
    torch.testing.assert_close(model.L, plain.L)
    assert all(math.isfinite(value) for value in model.obj)
    factor = getattr(model, side)
    if prior == "hmm_pos":
        assert (factor >= 0).all()
    elif prior == "hmm_neg":
        assert (factor <= 0).all()


def test_side_and_model_kwargs_are_independent():
    y = torch.ones(5, 7)
    model = cEBMF(y, prior_L="hmm", prior_F="hmm", prior_L_kwargs={"maxiter": 2}, prior_F_kwargs={"maxiter": 7})
    assert model.prior_L_fn is not model.prior_F_fn
    assert model.prior_L_fn.kwargs == {"maxiter": 2}
    assert model.prior_F_fn.kwargs == {"maxiter": 7}
    cEBMF(y, prior_F="hmm", prior_F_kwargs={"maxiter": 11})
    assert model.prior_F_fn.kwargs == {"maxiter": 7}
    assert {"hmm", "hmm_pos", "hmm_neg"} <= set(PRIOR_REGISTRY.list_priors())


def test_existing_order_defines_adjacency():
    y, se = tensor([0.1, 0.2, 0.8, 1.2, 1.6, 2.0]), tensor(0.7)
    order = torch.tensor([0, 3, 1, 4, 2, 5])
    kwargs = {"mu": [0, 2], "prior_sd": [0], "maxiter": 0}
    original = fit_ash_hmm(y, se, **kwargs)
    shuffled = fit_ash_hmm(y[order], se, **kwargs)
    assert not torch.allclose(original.post_mean[order], shuffled.post_mean)


def test_both_side_warnings_and_absence_without_covariates():
    y = torch.ones(8, 12)
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        cEBMF(y, prior_L="hmm", prior_F="hmm_pos")
    assert not caught
    with pytest.warns(UserWarning, match="HMM specified") as caught:
        cEBMF(y, prior_L="hmm", prior_F="hmm_pos", X_l=torch.arange(8), X_f=torch.arange(12))
    assert len(caught) == 2


def test_rna_style_fit_with_missing_entries():
    generator = torch.Generator().manual_seed(19)
    loading = (torch.arange(12) > 3).double()
    factor = torch.cat((torch.zeros(10), torch.ones(20) * 2, torch.zeros(10))).double()
    y = loading[:, None] * factor + 0.1 * torch.randn(12, 40, generator=generator, dtype=torch.float64)
    y[1, 4] = y[5, 21] = torch.nan
    y[:, 15] = torch.nan
    model = cEBMF(
        y,
        K=1,
        prior_L="gbinary",
        prior_F="hmm_pos",
        device=torch.device("cpu"),
        prior_F_kwargs={"maxiter": 8, "penalty": 1.5},
        allow_backfitting=False,
    )
    model.initialise_factors(L=loading[:, None], F=factor[:, None])
    model.fit(3)
    assert torch.isfinite(model.F).all() and torch.isfinite(model.L).all()
    assert (model.F >= 0).all() and all(math.isfinite(obj) for obj in model.obj)
    assert model.F[10:30].mean() > model.F[:10].mean() + 0.5


def test_refitting_does_not_reuse_pruned_grid_and_maxiter_overrides_epochs():
    y, se = tensor([0.1, 0, 2.1, 1.9, 0.2]), tensor(0.3)
    result = hmm_posterior_means(None, y, se, n_epochs=1, maxiter=3)
    again = hmm_posterior_means(torch.randn(17, 4), y, se, model_param={"mu": tensor([0])}, maxiter=3)
    assert result.iterations == 3
    torch.testing.assert_close(result.post_mean, again.post_mean)


@pytest.mark.parametrize("solver", [hmm_pos_posterior_means, hmm_neg_posterior_means])
def test_one_sided_adapter_does_not_create_a_spike_on_a_null_sequence(solver):
    y = torch.zeros(100, dtype=torch.float64)
    result = solver(None, y, torch.ones_like(y), n_epochs=10)
    assert result.post_mean.abs().max() < 1e-4
    # The first coordinate must not prevent pruning an unsupported factor.
    assert result.pi0_null.min() > 0.999
    assert (result.objective_history.diff() >= -1e-9).all()


@pytest.mark.parametrize("start,stop", [(0, 1), (0, 20), (40, 60), (99, 100)])
def test_learning_initial_probabilities_preserves_real_boundary_and_interior_signal(start, stop):
    y = torch.zeros(100, dtype=torch.float64)
    y[start:stop] = 5
    result = hmm_pos_posterior_means(None, y, torch.full_like(y, 0.25), n_epochs=10)
    assert result.post_mean[start:stop].min() > 4.5
    assert result.post_mean[y == 0].max() < 0.01
    assert result.pi0_null[start:stop].max() < 0.01


def test_hmm_adapter_can_keep_explicit_initial_probabilities_fixed():
    y, se = torch.zeros(100, dtype=torch.float64), tensor(1)
    options = dict(
        mu=[0, 1], prior_sd=[0], init_prob=[0.1, 0.9], estimate_init=False,
        maxiter=5, learn_state_means=False, prune_states=False,
    )
    result = hmm_pos_posterior_means(None, y, se, **options)
    reference = fit_ash_hmm(y, se, nonnegative_state_means=True, **options)
    torch.testing.assert_close(result.model_param["init_prob"], tensor([0.1, 0.9]))
    torch.testing.assert_close(result.post_mean, reference.post_mean)
    torch.testing.assert_close(result.loss, reference.loss)


def test_penalty_favors_transitions_to_zero():
    y, se = tensor([0.1, -0.3, 1.8, 1.3, -1.7, -1.1, 0.2, 0.4]), tensor(0.5)
    kwargs = {
        "mu": [0, 1.4, -1.2],
        "prior_sd": [0, 0.3, 1],
        "maxiter": 1,
        "learn_state_means": False,
        "prune_states": False,
    }
    neutral = hmm_posterior_means(None, y, se, penalty=1.0, **kwargs)
    penalized = hmm_posterior_means(None, y, se, penalty=1.5, **kwargs)
    assert (penalized.model_param["transition"][:, 0] > neutral.model_param["transition"][:, 0]).all()
    # The non-null atoms lie at nonzero centers and should not get a spike penalty.
    torch.testing.assert_close(penalized.model_param["mixture_weight"], neutral.model_param["mixture_weight"])
    torch.testing.assert_close(neutral.objective_history, neutral.history)


def test_single_adaptive_state_has_the_ash_spike_penalty():
    y, se, sd, initial = tensor([0.1, 0.2, 1.5, -0.8]), tensor(0.5), tensor([0, 1]), tensor([0.4, 0.6])
    result = fit_ash_hmm(
        y, se, mu=[0], prior_sd=sd, init_rho=initial[None], null_state="adaptive",
        penalty=1.5, maxiter=1, learn_state_means=False, prune_states=False,
    )
    component_log = torch.distributions.Normal(0, (se.square() + sd.square()).sqrt()).log_prob(y[:, None])
    counts = (component_log + initial.log()).softmax(1).sum(0) + tensor([0.5, 0])
    expected_weights = counts / counts.sum()
    torch.testing.assert_close(result.model_param["mixture_weight"][0], expected_weights)
    expected_ll = torch.logsumexp(component_log + expected_weights.log(), dim=1).sum()
    torch.testing.assert_close(result.loss, -expected_ll)
    torch.testing.assert_close(result.objective, expected_ll + 0.5 * expected_weights[0].log())


@pytest.mark.parametrize("penalty", [1.0, 1.5, 20.0])
def test_penalty_objective_and_unpenalized_loss(penalty):
    y, se = tensor([0.1, -0.3, 1.8, 1.3, -1.7, -1.1, 0.2, 0.4]), tensor([0.5] * 8)
    result = fit_ash_hmm(
        y, se, mu=[0, 1.4, -1.2], prior_sd=[0, 0.3, 1], null_state="adaptive",
        estimate_init=True, penalty=penalty, maxiter=12, learn_state_means=False, prune_states=False,
    )
    params = result.model_param
    emission = torch.logsumexp(
        _component_log_emission(y, se, params["mu"], params["prior_sd"], False) + params["mixture_weight"].log(), 2
    )
    ll, _, _ = _log_smoother(emission, params["transition"], params["init_prob"])
    log_null = params["transition"][:, 0].log().sum() + params["init_prob"][0].log()
    log_null += params["mixture_weight"][0, 0].log()
    torch.testing.assert_close(result.loss, -ll)
    torch.testing.assert_close(result.history[-1], ll)
    torch.testing.assert_close(result.objective, ll + (penalty - 1) * log_null)
    torch.testing.assert_close(result.objective_history[-1], result.objective)
    assert (result.objective_history.diff() >= -1e-9).all()
    assert normal_means_loglik(y, se, result.post_mean, result.post_mean2) + result.loss >= -1e-9


def test_penalty_objective_is_recomputed_after_pruning():
    result = fit_ash_hmm(
        tensor([0.1, -0.1, 0]), tensor(0.1), mu=[0, 10, -10], prior_sd=[0],
        penalty=1.5, maxiter=1, prune_start=1, prune_every=1, prune_max_fraction=0.9,
    )
    assert result.state_counts == [3, 1]
    torch.testing.assert_close(result.objective, result.log_likelihood)
    torch.testing.assert_close(result.objective_history[-1], result.objective)


@pytest.mark.parametrize("penalty", [0, -1, 0.5, math.inf, math.nan, True])
def test_invalid_penalty_is_rejected(penalty):
    with pytest.raises(ValueError, match="penalty must be finite and >= 1"):
        hmm_posterior_means(None, tensor([0.1, 1.0]), tensor(0.5), penalty=penalty)


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA unavailable")
def test_cuda_matches_cpu():
    y, se = tensor([0, 0.2, 2.1, 2.0, -1.2]), tensor([0.3] * 5)
    cpu = fit_ash_hmm(y, se, maxiter=4)
    gpu = fit_ash_hmm(y.cuda(), se.cuda(), maxiter=4)
    assert gpu.post_mean.device.type == gpu.loss.device.type == "cuda"
    torch.testing.assert_close(cpu.post_mean, gpu.post_mean.cpu())
    assert gpu.lfsr.device.type == "cuda"
    torch.testing.assert_close(cpu.lfsr, gpu.lfsr.cpu())
