# build docker image and push to github registry
name: Build and Push Docker Image
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cebmf_torch:${{ github.sha }} 
            ghcr.io/${{ github.repository_owner }}/cebmf_torch:latest